### ISSUE TITLE
Error while updating the content java.nio.file.InvalidPathException: Illegal char <:> at index 2:

### ISSUE THREAD

**Issue by zhujiajun917** [carlrobertoh/CodeGPT#130]
when  CodeGPT generate the code, it failed with:Something went wrong. And I get the message: 
`Error while updating the content

java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:\Users\intpl\AppData\Local\Temp\temp.py
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.nnthink.aixcoder.listener.CodeSyncListener.<init>(CodeSyncListener.java:40)
	at com.nnthink.aixcoder.listener.AixEditorFactoryListener.editorCreated(AixEditorFactoryListener.java:81)
	at com.nnthink.aixcoder.listener.AixEditorFactoryListener.editorCreated(AixEditorFactoryListener.java:40)
	at jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy1/jdk.proxy1.$Proxy120.editorCreated(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:208)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:195)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatEditor.<init>(ChatEditor.java:54)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatMessageResponseBody.createCodeBlockEditor(ChatMessageResponseBody.java:231)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatMessageResponseBody.prepareProcessingCodeResponse(ChatMessageResponseBody.java:187)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatMessageResponseBody.update(ChatMessageResponseBody.java:104)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatMessageResponseBody.update(ChatMessageResponseBody.java:89)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabPanel$3.handleMessage(ChatToolWindowTabPanel.java:200)
	at ee.carlrobert.codegpt.client.RequestHandler$1.process(RequestHandler.java:48)
	at java.desktop/javax.swing.SwingWorker$3.run(SwingWorker.java:423)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

**Comment by carlrobertoh** [comment]
Thank you for reporting! I'll investigate the issue.

**Comment by zhujiajun917** [comment]
> Thank you for reporting! I'll investigate the issue.

Hi. How's the update on this question?

**Comment by zhujiajun917** [comment]
> Hi, could you please try to install the [pre-release](https://github.com/carlrobertoh/CodeGPT/releases/tag/2.0.4) package and see if it makes any difference? I haven't been able to reproduce it on my machine.

Yes, I try and get result as above. Pls help to check what is going on. Thanks.

**Comment by carlrobertoh** [comment]
You could try upgrading the plugin to the latest version (2.0.3) and see if anything changes.
I believe the temp files are clashing altho I wasn't able to reproduce it yet.

**Comment by carlrobertoh** [comment]
Closing this issue due to inactivity.
