### ISSUE TITLE
Use OpenAI account name option not working properly and blocking the plugin

### ISSUE THREAD

**Issue by sbcolom** [carlrobertoh/CodeGPT#131]
After updating the plugin to v2.0.0 Display name plugin option in setting was empty and "Use OpenAI account name" was enabled.
The plugin wasn't loading, you could only see "Nothing to show." in the plugin window. I checked the rider logs and found the stack trace of an exception: 
`SEVERE - #c.i.i.p.PluginManager - Cannot invoke "String.isEmpty()" because "this.displayName" is null
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.displayName" is null
	at ee.carlrobert.codegpt.settings.SettingsState.getDisplayName(SettingsState.java:89)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatLandingView.createDescription(ChatLandingView.java:55)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatLandingView.<init>(ChatLandingView.java:38)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabPanel.displayLandingView(ChatToolWindowTabPanel.java:75)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowPanel.initialize(ChatToolWindowPanel.java:24)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowPanel.<init>(ChatToolWindowPanel.java:17)
	at ee.carlrobert.codegpt.toolwindow.ProjectToolWindowFactory.createToolWindowContent(ProjectToolWindowFactory.java:18)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:548)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:527)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:983)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:920)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:629)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:599)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1979)`

After setting a Display Name and disabling the "Use OpenAI account name" got fixed.

**Comment by carlrobertoh** [comment]
Hi,

Please try upgrading to the latest version to see if the problem persists.
https://plugins.jetbrains.com/plugin/21056-codegpt/versions/stable/348034

Thank you!
