### ISSUE TITLE
java.io.IOException: java.net.NoRouteToHostException: No route to host

### ISSUE THREAD

**Issue by andyChenHuaYing** [carlrobertoh/CodeGPT#145]
[OkHttp https://api.openai.com/...] ERROR ee.carlrobert.openai.client.completion.CompletionEventSourceListener - Something went wrong.
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - java.io.IOException: java.net.NoRouteToHostException: No route to host
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at ee.carlrobert.openai.client.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:89)
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at okhttp3.internal.sse.RealEventSource.onFailure(RealEventSource.kt:91)
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - Caused by: java.net.NoRouteToHostException: No route to host
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at java.base/sun.nio.ch.Net.connect0(Native Method)
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at java.base/sun.nio.ch.Net.connect(Net.java:579)
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at java.base/sun.nio.ch.Net.connect(Net.java:568)
2023-06-21 09:57:37,545 [63206632]   INFO - STDERR - 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at java.base/java.net.Socket.connect(Socket.java:633)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2023-06-21 09:57:37,546 [63206633]   INFO - STDERR - 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
2023-06-21 09:57:37,547 [63206634]   INFO - STDERR - 	... 3 more
2023-06-21 09:57:37,547 [63206634]   INFO - STDERR - 	Suppressed: java.net.SocketTimeoutException: Connect timed out
2023-06-21 09:57:37,547 [63206634]   INFO - STDERR - 		at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
2023-06-21 09:57:37,547 [63206634]   INFO - STDERR - 		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
2023-06-21 09:57:37,547 [63206634]   INFO - STDERR - 		... 22 more

**Comment by carlrobertoh** [comment]
Hi, could you give me more details on how this error occurred?
