### ISSUE TITLE
414 - Request-URI Too Large

### ISSUE THREAD

**Issue by pixkk** [carlrobertoh/CodeGPT#279]
### What happened?

When i typed next string in chat:

$greater = $number1->greaterThan($number2);
$greater return false (not true

it returns this error.
![image](https://github.com/carlrobertoh/CodeGPT/assets/30828435/904c6689-c373-44ad-83b6-145f06eb7ac2)

### Relevant log output or stack trace

```shell
<html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

   
   java.lang.RuntimeException
	at ee.carlrobert.llm.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:112)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce

![image](https://github.com/carlrobertoh/CodeGPT/assets/30828435/87055bd1-f16d-4c12-a49a-93fce048c3c2)

### CodeGPT version

2.2.3

### Operating System

Windows

**Comment by pixkk** [comment]
After this request, all next requests return 414 error. I need open new chat to resolve this problem :(

**Comment by pixkk** [comment]
UPD: The problem occurs when communicating in one chat for a long time.

**Comment by carlrobertoh** [comment]
Yeah, I knew it would happen sooner or later. You.com is using GET method for their completion service, and because of that, the entire prompt must fit in the request URL which has limitations.

Unfortunately, there's nothing I can do on my side.

**Comment by carlrobertoh** [comment]
Workaround would be to clear the active session (i.e. open a new chat tab).

**Comment by pixkk** [comment]
Thanks for response!
