### ISSUE TITLE
Append response text outside of the main GUI thread

### ISSUE THREAD

**Issue by carlrobertoh** [carlrobertoh/CodeGPT#31]
```
Freeze in EDT for 12 seconds
IDE KILLED! Sampled time: 4500ms, sampling rate: 100ms, GC time: 58ms (0%), Class loading: 0%, debug agent: on

com.intellij.diagnostic.Freeze
	at java.base@17.0.6/java.lang.Object.wait(Native Method)
	at java.base@17.0.6/java.lang.Object.wait(Object.java:338)
	at java.desktop/javax.swing.text.AbstractDocument.readLock(AbstractDocument.java:1421)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:942)
	at java.desktop/javax.swing.plaf.basic.BasicTextAreaUI.getPreferredSize(BasicTextAreaUI.java:121)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1721)
```

**Comment by carlrobertoh** [comment]
```
Freeze in EDT for 12 seconds
IDE KILLED! Sampled time: 4500ms, sampling rate: 100ms, GC time: 58ms (0%), Class loading: 0%, debug agent: on

com.intellij.diagnostic.Freeze
	at java.base@17.0.6/java.lang.Object.wait(Native Method)
	at java.base@17.0.6/java.lang.Object.wait(Object.java:338)
	at java.desktop/javax.swing.text.AbstractDocument.readLock(AbstractDocument.java:1421)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:942)
	at java.desktop/javax.swing.plaf.basic.BasicTextAreaUI.getPreferredSize(BasicTextAreaUI.java:121)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1721)
```
