### ISSUE TITLE
IDE reports error when input is wider than the window

### ISSUE THREAD

**Issue by MTheProgrammer** [carlrobertoh/CodeGPT#32]
I was generating unit tests with my custom prompt. The output was wider than the chat panel resulting in truncation of the result from OpenApi and error.
Below is the stacktrace.
```
java.lang.IndexOutOfBoundsException: len=-10
	at java.desktop/sun.font.FontDesignMetrics.charsWidth(FontDesignMetrics.java:505)
	at org.fife.ui.rsyntaxtextarea.TokenImpl.getWidthUpTo(TokenImpl.java:601)
	at org.fife.ui.rsyntaxtextarea.TokenImpl.getWidth(TokenImpl.java:570)
	at org.fife.ui.rsyntaxtextarea.TokenUtils.getSubTokenList(TokenUtils.java:122)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.calculateLineCount(WrappedSyntaxView.java:1188)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.getPreferredSpan(WrappedSyntaxView.java:1236)
	at java.desktop/javax.swing.text.View.getMinimumSpan(View.java:248)
	at java.desktop/javax.swing.text.BoxView.calculateMajorAxisRequirements(BoxView.java:872)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:931)
	at java.desktop/javax.swing.text.BoxView.getPreferredSpan(BoxView.java:546)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView.getMinimumSpan(WrappedSyntaxView.java:594)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.getMinimumSpan(BasicTextUI.java:1473)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getMinimumSize(BasicTextUI.java:980)
	at java.desktop/javax.swing.plaf.basic.BasicTextAreaUI.getMinimumSize(BasicTextAreaUI.java:135)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1808)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:475)
	at java.desktop/javax.swing.BoxLayout.preferredLayoutSize(BoxLayout.java:293)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1730)
	at com.intellij.ui.components.JBScrollPane$Layout.layoutContainer(JBScrollPane.java:535)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validate(Container.java:1660)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:760)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:758)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:757)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1908)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:475)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by carlrobertoh** [comment]
Did the error occurred in the custom prompt dialog, or after you sent the prompt(clicked Send)?

**Comment by carlrobertoh** [comment]
Closing the issue.
New UI has been implemented which no longer uses the `rsyntaxtextarea` library, with the exception of those whose IDE doesn't support `JBCefApp`.
