### ISSUE TITLE
Chat window freezes after longer response and can't be reopened

### ISSUE THREAD

**Issue by MTheProgrammer** [carlrobertoh/CodeGPT#33]
Actually it is just transparent, because I was unable to click on the editor area which was covered by the chat panel.
Only IDE restart helps.

```
java.lang.Error: Error: could not match input
	at org.fife.ui.rsyntaxtextarea.modes.MarkdownTokenMaker.zzScanError(MarkdownTokenMaker.java:1360)
	at org.fife.ui.rsyntaxtextarea.modes.MarkdownTokenMaker.yylex(MarkdownTokenMaker.java:1771)
	at org.fife.ui.rsyntaxtextarea.modes.MarkdownTokenMaker.getTokenList(MarkdownTokenMaker.java:1163)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.getTokenListForLine(RSyntaxDocument.java:433)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.calculateLineCount(WrappedSyntaxView.java:1180)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.getPreferredSpan(WrappedSyntaxView.java:1236)
	at java.desktop/javax.swing.text.View.getMinimumSpan(View.java:248)
	at java.desktop/javax.swing.text.BoxView.calculateMajorAxisRequirements(BoxView.java:872)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:931)
	at java.desktop/javax.swing.text.BoxView.getPreferredSpan(BoxView.java:546)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView.getMinimumSpan(WrappedSyntaxView.java:594)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.getMinimumSpan(BasicTextUI.java:1473)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getMinimumSize(BasicTextUI.java:980)
	at java.desktop/javax.swing.plaf.basic.BasicTextAreaUI.getMinimumSize(BasicTextAreaUI.java:135)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1808)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:475)
	at java.desktop/javax.swing.BoxLayout.preferredLayoutSize(BoxLayout.java:293)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1730)
	at com.intellij.ui.components.JBScrollPane$Layout.layoutContainer(JBScrollPane.java:535)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validate(Container.java:1660)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:760)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:758)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:757)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1908)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:475)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by carlrobertoh** [comment]
Hi

Could this [issue](https://github.com/carlrobertoh/CodeGPT/issues/31#issue-1617483252) be related? Might want to wait until 1.4.1 release is approved or try downloading/installing it manually.

Best regards

**Comment by MTheProgrammer** [comment]
I've updated today and it seems to be fixed.
