### ISSUE TITLE
Code Inline Completion Error Message

### ISSUE THREAD

**Issue by dginovker** [carlrobertoh/CodeGPT#367]
### What happened?

Enabled code completion. It wasn't working (said it timed out), so I went to the plugin settings and stopped and restarted my LLaMA server. Saw this message in the bottom right afterwards, although I can't guarantee the message only appeared at that time and not earlier

(I recognize the stacktrace says openai in it.. I was using OpenAI before, but I'm 95% sure it was set to LLaMA for at least a while at the time the stacktrace happened)

### Relevant log output or stack trace

```shell
java.lang.IndexOutOfBoundsException: chars sequence.length:12458, start:2462, end:12462
	at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:20)
	at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:206)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$getText$3(DocumentImpl.java:955)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:955)
	at ee.carlrobert.codegpt.codecompletions.InfillRequestDetails.truncateText(InfillRequestDetails.java:46)
	at ee.carlrobert.codegpt.codecompletions.InfillRequestDetails.fromDocumentWithCustomRange(InfillRequestDetails.java:39)
	at ee.carlrobert.codegpt.codecompletions.InfillRequestDetails.fromDocumentWithMaxOffset(InfillRequestDetails.java:23)
	at ee.carlrobert.codegpt.codecompletions.CodeCompletionService.handleCompletions(CodeCompletionService.java:94)
	at ee.carlrobert.codegpt.codecompletions.CodeCompletionListenerBinder$EditorDocumentListener.lambda$documentChangedNonBulk$0(CodeCompletionListenerBinder.java:135)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1444)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### CodeGPT version

2.3.0

### Operating System

Linux

**Comment by dginovker** [comment]
Just got it again, pretty much identical stacktrace, after using the autocomplete then hitting `ctrl + alt + L` to format my code

<details>
<summary>Stack trace</summary>

```
java.lang.IndexOutOfBoundsException: chars sequence.length:13750, start:3835, end:13835
	at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:20)
	at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:206)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$getText$3(DocumentImpl.java:955)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:955)
	at ee.carlrobert.codegpt.codecompletions.InfillRequestDetails.truncateText(InfillRequestDetails.java:46)
	at ee.carlrobert.codegpt.codecompletions.InfillRequestDetails.fromDocumentWithCustomRange(InfillRequestDetails.java:39)
	at ee.carlrobert.codegpt.codecompletions.InfillRequestDetails.fromDocumentWithMaxOffset(InfillRequestDetails.java:23)
	at ee.carlrobert.codegpt.codecompletions.CodeCompletionService.handleCompletions(CodeCompletionService.java:94)
	at ee.carlrobert.codegpt.codecompletions.CodeCompletionListenerBinder$EditorDocumentListener.lambda$documentChangedNonBulk$0(CodeCompletionListenerBinder.java:135)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1444)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
</details>

**Comment by carlrobertoh** [comment]
Thanks for reporting! I will look into it.
