### ISSUE TITLE
PluginException: Migrate ee.carlrobert.codegpt.PluginStartupActivity to ProjectActivity

### ISSUE THREAD

**Issue by reijerh** [carlrobertoh/CodeGPT#372]
### What happened?

Guessing this is more of a warning than an error, but hard to tell because it still throws an exception. Saw this in the idea.log  (plugin does load and work correctly):
`PluginException: Migrate ee.carlrobert.codegpt.PluginStartupActivity to ProjectActivity`

### Relevant log output or stack trace

```shell
2024-02-19 13:27:09,023 [  25897]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate ee.carlrobert.codegpt.PluginStartupActivity to ProjectActivity [Plugin: ee.carlrobert.chatgpt]
com.intellij.diagnostic.PluginException: Migrate ee.carlrobert.codegpt.PluginStartupActivity to ProjectActivity [Plugin: ee.carlrobert.chatgpt]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:275)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### CodeGPT version

2.3.0

### Operating System

Linux

**Comment by carlrobertoh** [comment]
Should be fixed in the latest version. Please reopen the ticket if it's still reproducible.
