### ISSUE TITLE
getting IDE error and can't use this pulgin at all

### ISSUE THREAD

**Issue by Azim-Sabbir** [carlrobertoh/CodeGPT#417]
### What happened?

<img width="741" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/60954493/f87ea998-5a86-4ab7-839a-fedafb99009a">

every time a click on the plugin, it says IDE error and there is no way i can change the configs form settings nor use this plugin.ive tried updating my IDE, restarting, reinstalling the plugin but nothing works.

### Relevant log output or stack trace

```shell
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at ee.carlrobert.llm.client.openai.completion.OpenAIChatCompletionModel.findByCode(OpenAIChatCompletionModel.java:45)
	at ee.carlrobert.codegpt.toolwindow.chat.ui.textarea.ModelComboBoxAction.updateTemplatePresentation(ModelComboBoxAction.java:150)
	at ee.carlrobert.codegpt.toolwindow.chat.ui.textarea.ModelComboBoxAction.<init>(ModelComboBoxAction.java:52)
	at ee.carlrobert.codegpt.toolwindow.chat.ui.textarea.UserPromptTextAreaHeader.<init>(UserPromptTextAreaHeader.java:32)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabPanel.createUserPromptPanel(ChatToolWindowTabPanel.java:263)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabPanel.createRootPanel(ChatToolWindowTabPanel.java:283)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabPanel.<init>(ChatToolWindowTabPanel.java:81)
	at ee.carlrobert.codegpt.toolwindow.chat.standard.StandardChatToolWindowTabPanel.<init>(StandardChatToolWindowTabPanel.java:26)
	at ee.carlrobert.codegpt.toolwindow.chat.standard.StandardChatToolWindowPanel.init(StandardChatToolWindowPanel.java:59)
	at ee.carlrobert.codegpt.toolwindow.chat.standard.StandardChatToolWindowPanel.<init>(StandardChatToolWindowPanel.java:34)
	at ee.carlrobert.codegpt.toolwindow.ProjectToolWindowFactory.createToolWindowContent(ProjectToolWindowFactory.java:18)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:594)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:573)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1035)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:969)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:672)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:641)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2244)
	at com.intellij.openapi.wm.impl.SquareAnActionButton.setSelected(SquareStripeButton.kt:176)
	at com.intellij.ui.ToggleActionButton.actionPerformed(ToggleActionButton.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:381)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:524)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:635)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:580)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:580)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### CodeGPT version

2.5.1

### Operating System

macOS

**Comment by Azim-Sabbir** [comment]
**i'm using PhpStorm 2023.3 by the way**

**Comment by Bikkies** [comment]
Did you have an older version of the plugin installed at one point? I also had an issue like this, and the fix for me was to remove all of the old config that sits in AppData\Roaming\JetBrains\PhpStorm2023.3\options.

Uninstall the plugin, delete all the files starting with CodeGPT_ in there, restart phpstorm and reinstall the plugin

**Comment by saroele** [comment]
I had the same issue (on linux Mint).  I have deleted 2 files:
`~/.config/JetBrains/PyCharm2023.2/options/CodeGPT_OpenAISettings_210.xml ~/.config/JetBrains/PyCharm2023.3/options/CodeGPT_OpenAISettings_210.xml`

After restarting pycharm, CodeGPT loaded as expected.

**Comment by reneleonhardt** [comment]
@Azim-Sabbir Can you still reproduce the problem after you followed https://github.com/carlrobertoh/CodeGPT/issues/417#issuecomment-2011171518 instructions to reinstall?

**Comment by bishopandco** [comment]
> EDIT: I'm not sure where these files live on a Mac

🍏 --> ``` ~/Library/Application\ Support/JetBrains/RustRover2023.3/ ```

**Comment by Azim-Sabbir** [comment]
> @Azim-Sabbir Can you still reproduce the problem after you followed [#417 (comment)](https://github.com/carlrobertoh/CodeGPT/issues/417#issuecomment-2011171518) instructions to reinstall?

@reneleonhardt im using MacOs... so dont know where these files are located.

**Comment by PhilKes** [comment]
> > @Azim-Sabbir Can you still reproduce the problem after you followed [#417 (comment)](https://github.com/carlrobertoh/CodeGPT/issues/417#issuecomment-2011171518) instructions to reinstall?
> 
> @reneleonhardt im using MacOs... so dont know where these files are located.

Maybe you oversaw https://github.com/carlrobertoh/CodeGPT/issues/417#issuecomment-2057241834, can you check the path mentioned by @bishopandco ?

**Comment by Azim-Sabbir** [comment]
Thank you so much, it solved the issue. @bishopandco @PhilKes
