### ISSUE TITLE
IDE internal error

### ISSUE THREAD

**Issue by SikamikanikoBG** [carlrobertoh/CodeGPT#429]
### What happened?

At some point the CodeGPT stopped working Pycharm. 

![image](https://github.com/carlrobertoh/CodeGPT/assets/46193504/b6b69308-4d4d-43db-95db-ea25d6a06847)
![image](https://github.com/carlrobertoh/CodeGPT/assets/46193504/e0702e8b-89b5-4469-9146-924015420b66)

### Relevant log output or stack trace

```shell
Something went wrong

java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.base/java.lang.String.replace(String.java:2961)
	at ee.carlrobert.codegpt.completions.CompletionRequestProvider.buildCustomOpenAIChatCompletionRequest(CompletionRequestProvider.java:221)
	at ee.carlrobert.codegpt.completions.CompletionRequestProvider.buildCustomOpenAIChatCompletionRequest(CompletionRequestProvider.java:207)
	at ee.carlrobert.codegpt.completions.CompletionRequestService.getChatCompletionAsync(CompletionRequestService.java:80)
	at ee.carlrobert.codegpt.completions.CompletionRequestHandler.startCall(CompletionRequestHandler.java:49)
	at ee.carlrobert.codegpt.completions.CompletionRequestHandler$CompletionRequestWorker.doInBackground(CompletionRequestHandler.java:77)
	at ee.carlrobert.codegpt.completions.CompletionRequestHandler$CompletionRequestWorker.doInBackground(CompletionRequestHandler.java:66)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### CodeGPT version

2.5.1

### Operating System

Windows

**Comment by SikamikanikoBG** [comment]
To resume using it - I have to delete the options files in options dir (C:\Users\...\AppData\Roaming\JetBrains\PyCharmCE2023.3\options) 
which restarts completely the plugin. After that I have to setup again the api keys or Ollama settings and it starts to work properly.

![image](https://github.com/carlrobertoh/CodeGPT/assets/46193504/fca4b5d4-96ba-40f7-a6c4-8052f44184a0)

**Comment by carlrobertoh** [comment]
Thanks for reporting! I will take a look.

**Comment by reneleonhardt** [comment]
This bug has been fixed on 2024-03-27: https://github.com/carlrobertoh/CodeGPT/commit/6255bf9eb6f2ba516d0ee582e1d78a9fad5d478f#diff-f467f3a210aeea4d765c37f818fd7514c7706f4d87b65e9dbe69ebd9e22e00ddR207
But there has been no new release since 2.5.1, that's why this bug can still occur.
