### ISSUE TITLE
Input is not UTF-8: emoji

### ISSUE THREAD

**Issue by kodeninja** [carlrobertoh/CodeGPT#444]
### What happened?

Inserting an emoji (🟢) from the MacOS `Character Viewer` in the Chat area causes the plugin to crash.

**Environment**:

```
PyCharm 2024.1 (Professional Edition)
Build #PY-241.14494.241, built on March 28, 2024
Licensed to Ask.com - IAC Search and Media / Robin Sharma
Subscription is active until May 18, 2024.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  ee.carlrobert.chatgpt (2.5.1)
  com.intellij.kubernetes (241.14494.150)
  com.intellij.ml.llm (241.14494.240)
  com.github.copilot (1.5.1.5285)
```

### Relevant log output or stack trace

```shell
java.lang.AssertionError: Input is not UTF-8: Success emoji: ?
	at com.knuddels.jtokkit.Cl100kParser.split(Cl100kParser.java:32)
	at com.knuddels.jtokkit.EncodingFactory$Cl100kGptBytePairEncoding.encodeOrdinaryInternal(EncodingFactory.java:182)
	at com.knuddels.jtokkit.GptBytePairEncoding.encodeOrdinaryInternal(GptBytePairEncoding.java:71)
	at com.knuddels.jtokkit.GptBytePairEncoding.encodeInternal(GptBytePairEncoding.java:52)
	at com.knuddels.jtokkit.GptBytePairEncoding.countTokens(GptBytePairEncoding.java:104)
	at ee.carlrobert.codegpt.EncodingManager.countTokens(EncodingManager.java:51)
	at ee.carlrobert.codegpt.toolwindow.chat.ui.textarea.TotalTokensPanel.updateUserPromptTokens(TotalTokensPanel.java:107)
	at ee.carlrobert.codegpt.toolwindow.chat.ui.textarea.UserPromptTextArea$4.textChanged(UserPromptTextArea.java:105)
	at com.intellij.ui.DocumentAdapter.insertUpdate(DocumentAdapter.java:15)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:226)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:780)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:739)
	at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:698)
	at java.desktop/javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1339)
	at java.desktop/javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2943)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2991)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2905)
	at java.desktop/javax.swing.text.JTextComponent.replaceInputMethodText(JTextComponent.java:4833)
	at java.desktop/javax.swing.text.JTextComponent.processInputMethodEvent(JTextComponent.java:4581)
	at java.desktop/java.awt.Component.processEvent(Component.java:6439)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:698)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:105)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### CodeGPT version

2.5.1

### Operating System

macOS

**Comment by reneleonhardt** [comment]
Hello @kodeninja thank you for reporting!
I could fix this particular crash, but I couldn't reproduce it, I couldn't find the `Success emoji: ` your log showed 😅
Can you provide a search text for the current macOS 14.4.1 when I'm using `Show Emoji & Symbols`?
What are your system settings for language and keyboard input source in that moment?

**Comment by kodeninja** [comment]
@reneleonhardt, it was mentioned in the **What happened?** section: 🟢.
