### ISSUE TITLE
Cannot be used in Android Studio Iguana shows the exception: java.util.NoSuchElementException: No value present 

### ISSUE THREAD

**Issue by kurosaki-tisak** [carlrobertoh/CodeGPT#484]
### What happened?

It cannot be used in Android Studio Iguana | 2023.2.1 Patch 2
It shows the exception in the following screenshot:

![Screenshot 2567-04-22 at 11 16 03](https://github.com/carlrobertoh/CodeGPT/assets/25000465/90c19ef0-9836-4e1c-9d74-b619c192a447)

Please help!

### Relevant log output or stack trace

```shell
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at ee.carlrobert.llm.client.openai.completion.OpenAIChatCompletionModel.findByCode(OpenAIChatCompletionModel.java:46)
	at ee.carlrobert.codegpt.toolwindow.chat.ui.textarea.ModelComboBoxAction.updateTemplatePresentation(ModelComboBoxAction.java:149)
	at ee.carlrobert.codegpt.toolwindow.chat.ui.textarea.ModelComboBoxAction.<init>(ModelComboBoxAction.java:50)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabPanel.createUserPromptTextAreaHeader(ChatToolWindowTabPanel.java:293)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabPanel.createUserPromptPanel(ChatToolWindowTabPanel.java:277)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabPanel.createRootPanel(ChatToolWindowTabPanel.java:364)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabPanel.<init>(ChatToolWindowTabPanel.java:79)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowPanel.init(ChatToolWindowPanel.java:99)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowPanel.<init>(ChatToolWindowPanel.java:47)
	at ee.carlrobert.codegpt.toolwindow.ProjectToolWindowFactory.createToolWindowContent(ProjectToolWindowFactory.java:17)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:554)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:533)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1014)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:951)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:658)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:627)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2051)
	at com.intellij.openapi.wm.impl.SquareAnActionButton.setSelected(SquareStripeButton.kt:172)
	at com.intellij.ui.ToggleActionButton.actionPerformed(ToggleActionButton.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:520)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:592)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

### CodeGPT version

2.6.2-222

### Operating System

macOS

**Comment by reneleonhardt** [comment]
Thank you for reporting! Have you been able to open the CodeGPT panel before, select an OpenAI service/model and work successfully?
Or is this a fresh install of the plugin and you're using it for the first time?

**Comment by kurosaki-tisak** [comment]
@reneleonhardt Yes! I have used it before

**Comment by reneleonhardt** [comment]
Did you just update the plugin or were you using it without problems the last time you opened Android Studio?

**Comment by kurosaki-tisak** [comment]
@reneleonhardt I used it without problems last time with the Android Studio Flamingo and Giraffe version
But after that, the error appears, as you can see earlier.

**Comment by reneleonhardt** [comment]
Does this mean that this was the first time you used Iguana (2023.2.1), did you just upgrade from Giraffe (2022.3.1)?
And you didn't just upgrade CodeGPT to 2.6.2 after the last time you used it successfully?

Can you open Settings / Tools / CodeGPT and switch to the last Service `LLaMA C/C++` before trying to open the panel?
Otherwise I believe the settings need to be cleared first.

**Comment by reneleonhardt** [comment]
I tried a fresh install of Iguana and CodeGPT, and there were no problems 😅
So maybe uninstalling and reinstalling CodeGPT could work, or cleaning settings.

But I'm afraid that any CodeGPT release after 2.6.2 will not work in Iguana (2023.2.1) anymore, only in Jellyfish (2023.3.1).
I find the official https://www.jetbrains.com/toolbox-app/ the easiest way to manage different versions/release candidates.

**Comment by kurosaki-tisak** [comment]
@reneleonhardt I tried a fresh install of Iguana and CodeGPT, but it still won't work!
I can't open Settings / Tools / CodeGPT, as the following screenshot:

<img width="983" alt="Screenshot 2567-04-22 at 18 58 58" src="https://github.com/carlrobertoh/CodeGPT/assets/25000465/4583a692-371d-48d5-99fa-2a7601365e4c">

It keep loading......

**Comment by carlrobertoh** [comment]
Hey, try removing all `CodeGPT_*.xml` settings files from the plugin's directory and then restart the IDE.
https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

For me, they would be accessible from `/Users/carlrobertoh/Library/Application Support/JetBrains/IntelliJIdea2024.1/options`

**Comment by reneleonhardt** [comment]
> I tried a fresh install of Iguana and CodeGPT

Sorry, I meant an even "fresher" install 😅 (Without settings directory)

**Comment by kurosaki-tisak** [comment]
@carlrobertoh It works!
@reneleonhardt Thank you for your support! 

You both saved me!

**Comment by reneleonhardt** [comment]
You're welcome, don't forget to upgrade to Jellyfish soon 😄
