### ISSUE TITLE
Failed authenticate with proxy

### ISSUE THREAD

**Issue by sboriskin287** [carlrobertoh/CodeGPT#586]
### What happened?

I getting error "Failed authenticate with proxy" upon using api.openai.com via proxy. Judging by capturing from wireshark there is no Authentication header with credentials for proxy. Also i attaching idea log.

### Relevant log output or stack trace

```shell
2024-05-30 14:40:10,535 [1139483]   FINE - #c.i.u.p.CommonProxy - CommonProxy.select called for socket://<proxy-ip-and-port>
2024-05-30 14:40:10,536 [1139484]   FINE - #c.i.u.p.CommonProxy - CommonProxy.select returns custom proxy for socket://<proxy-ip-and-port>, [DIRECT]
2024-05-30 14:40:10,566 [1139514]   WARN - #c.i.s.ComponentManagerImpl - ee.carlrobert.codegpt.telemetry.ui.TelemetryNotifications <clinit> requests com.intellij.ide.plugins.PluginUtil instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
2024-05-30 14:40:10,682 [1139630] SEVERE - #ee.carlrobert.codegpt.toolwindow.chat.ToolWindowCompletionResponseEventListener - Failed to authenticate with proxy
java.io.IOException: Failed to authenticate with proxy
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:476)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Steps to reproduce

1. Setup http proxy in idea
2. Send any query to openai api from plugin
3. Get a error

![wireshark-tracing](https://github.com/carlrobertoh/CodeGPT/assets/37264439/bff3cd80-cc4f-495f-92e6-ff95053d8f39)

### CodeGPT version

2.7.1

### Operating System

Windows

**Comment by sboriskin287** [comment]
![image](https://github.com/user-attachments/assets/599d7bdf-c528-4cd0-ac8d-cf4c91fac19b)
No, it's my own proxy server, and i seting exactly it in my IDEa settings
