### ISSUE TITLE
Bug in the context menu

### ISSUE THREAD

**Issue by rubydev** [carlrobertoh/CodeGPT#644]
### What happened?

<img width="575" alt="Screenshot 2024-08-06 at 13 14 35" src="https://github.com/user-attachments/assets/ce7698c1-7862-43e7-83ba-42cb28c323f8">

### Relevant log output or stack trace

```shell
com.intellij.diagnostic.PluginException: ID 'codegpt.NewChat' is already taken by action 'New Chat (Chat with CodeGPT)' (class ee.carlrobert.codegpt.actions.editor.AskAction)  (Plugin: CodeGPT). Action 'New Chat (Chat with CodeGPT)' (class ee.carlrobert.codegpt.actions.editor.AskAction) cannot use the same ID (plugin ee.carlrobert.chatgpt) [Plugin: ee.carlrobert.chatgpt]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.reportActionIdCollision(ActionManagerImpl.kt:2045)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction(ActionManagerImpl.kt:2125)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction$default(ActionManagerImpl.kt:2111)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.kt:957)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil.registerAction(EditorActionsUtil.java:89)
	at ee.carlrobert.codegpt.actions.editor.AskAction.<init>(AskAction.java:15)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil.refreshActions(EditorActionsUtil.java:49)
	at ee.carlrobert.codegpt.CodeGPTProjectActivity.execute(CodeGPTProjectActivity.kt:25)
	at com.intellij.ide.startup.impl.StartupManagerImpl$Companion$addActivityEpListener$1$extensionAdded$1.invokeSuspend(StartupManagerImpl.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

com.intellij.diagnostic.PluginException: ID 'codegpt.EditCode' is already taken by action 'Edit Code (Allow LLM to edit code directly in your editor)' (class ee.carlrobert.codegpt.actions.editor.EditCodeAction)  (Plugin: CodeGPT). Action 'Edit Code (Allow LLM to edit code directly in your editor)' (class ee.carlrobert.codegpt.actions.editor.EditCodeAction) cannot use the same ID (plugin ee.carlrobert.chatgpt) [Plugin: ee.carlrobert.chatgpt]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.reportActionIdCollision(ActionManagerImpl.kt:2045)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction(ActionManagerImpl.kt:2125)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction$default(ActionManagerImpl.kt:2111)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.kt:957)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil.registerAction(EditorActionsUtil.java:89)
	at ee.carlrobert.codegpt.actions.editor.BaseEditorAction.<init>(BaseEditorAction.java:21)
	at ee.carlrobert.codegpt.actions.editor.EditCodeAction.<init>(EditCodeAction.kt:18)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil.refreshActions(EditorActionsUtil.java:50)
	at ee.carlrobert.codegpt.CodeGPTProjectActivity.execute(CodeGPTProjectActivity.kt:25)
	at com.intellij.ide.startup.impl.StartupManagerImpl$Companion$addActivityEpListener$1$extensionAdded$1.invokeSuspend(StartupManagerImpl.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

com.intellij.diagnostic.PluginException: ID 'codegpt.CustomPrompt' is already taken by action 'Custom Prompt (Custom prompt description)' (class ee.carlrobert.codegpt.actions.editor.CustomPromptAction)  (Plugin: CodeGPT). Action 'Custom Prompt (Custom prompt description)' (class ee.carlrobert.codegpt.actions.editor.CustomPromptAction) cannot use the same ID (plugin ee.carlrobert.chatgpt) [Plugin: ee.carlrobert.chatgpt]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.reportActionIdCollision(ActionManagerImpl.kt:2045)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction(ActionManagerImpl.kt:2125)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction$default(ActionManagerImpl.kt:2111)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.kt:957)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil.registerAction(EditorActionsUtil.java:89)
	at ee.carlrobert.codegpt.actions.editor.BaseEditorAction.<init>(BaseEditorAction.java:21)
	at ee.carlrobert.codegpt.actions.editor.CustomPromptAction.<init>(CustomPromptAction.java:28)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil.refreshActions(EditorActionsUtil.java:51)
	at ee.carlrobert.codegpt.CodeGPTProjectActivity.execute(CodeGPTProjectActivity.kt:25)
	at com.intellij.ide.startup.impl.StartupManagerImpl$Companion$addActivityEpListener$1$extensionAdded$1.invokeSuspend(StartupManagerImpl.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

com.intellij.diagnostic.PluginException: ID 'codegpt.WriteTests' is already taken by action 'Write Tests (Write Tests)' (class ee.carlrobert.codegpt.actions.editor.EditorActionsUtil$1)  (Plugin: CodeGPT). Action 'Write Tests (Write Tests)' (class ee.carlrobert.codegpt.actions.editor.EditorActionsUtil$1) cannot use the same ID (plugin ee.carlrobert.chatgpt) [Plugin: ee.carlrobert.chatgpt]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.reportActionIdCollision(ActionManagerImpl.kt:2045)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction(ActionManagerImpl.kt:2125)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction$default(ActionManagerImpl.kt:2111)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.kt:957)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil.registerAction(EditorActionsUtil.java:89)
	at ee.carlrobert.codegpt.actions.editor.BaseEditorAction.<init>(BaseEditorAction.java:21)
	at ee.carlrobert.codegpt.actions.editor.BaseEditorAction.<init>(BaseEditorAction.java:27)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil$1.<init>(EditorActionsUtil.java:58)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil.lambda$refreshActions$2(EditorActionsUtil.java:58)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at ee.carlrobert.codegpt.actions.editor.EditorActionsUtil.refreshActions(EditorActionsUtil.java:55)
	at ee.carlrobert.codegpt.CodeGPTProjectActivity.execute(CodeGPTProjectActivity.kt:25)
	at com.intellij.ide.startup.impl.StartupManagerImpl$Companion$addActivityEpListener$1$extensionAdded$1.invokeSuspend(StartupManagerImpl.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### Steps to reproduce

macOS Sonoma 14.5
Rubymine 2024.1.4

### CodeGPT version

2.9.0-241.1

### Operating System

macOS

**Comment by carlrobertoh** [comment]
That's new. Could you please provide me with the contents of the context menu table data in the file `CodeGPT_ConfigurationSettings_210.xml`?

Also, as a temporary workaround, deleting this file should bring back the default state.

**Comment by rubydev** [comment]
It's working for me too. I don't know what happened. We can close this issue.
