### ISSUE TITLE
Custom OpenAI Error

### ISSUE THREAD

**Issue by JackCmd233** [carlrobertoh/CodeGPT#664]
### What happened?

As long as I write the code, the plug-in will report an error, whether AI is used or not.

For example, if I enter a carriage return line feed in the code, it will report an error.

### Relevant log output or stack trace

```shell
Unknown API response. Code: 422, Body: Failed to deserialize the JSON body into the target type: missing field `messages` at line 6 column 1

Unknown API response. Code: 422, Body: Failed to deserialize the JSON body into the target type: missing field `messages` at line 6 column 1

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Failed': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 7]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2567)
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2593)
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2601)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:765)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3018)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2052)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:780)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4992)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4898)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
	at ee.carlrobert.llm.client.openai.completion.OpenAITextCompletionEventSourceListener.getErrorDetails(OpenAITextCompletionEventSourceListener.java:43)
	at ee.carlrobert.llm.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:112)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Steps to reproduce

1. I am using deepseek AI model, it is compatible with OpenAI, so there should be no compatibility issues
2. If I switch from Custom OpenAI to OpenAI or any other model, there is no error.

### CodeGPT version

2.9.0.233

### Operating System

Windows

**Comment by JackCmd233** [comment]
I may have found the key to the problem

![Uploading Error.png…]()

**Comment by JackCmd233** [comment]
I may have found the key to the problem
close this option
<img width="1162" alt="Error" src="https://github.com/user-attachments/assets/41f31cb5-0ffe-4f2a-a8f6-2c0c9ad0b533">
