### ISSUE TITLE
InlineCompletionSingleSuggestion NoClassDefFoundError

### ISSUE THREAD

**Issue by dongxinxing** [carlrobertoh/CodeGPT#699]
use properties

pluginSinceBuild = 201
pluginUntilBuild = 241.1 

code completion  happen  exception

java.lang.NoClassDefFoundError: com/intellij/codeInsight/inline/completion/suggestion/InlineCompletionSingleSuggestion
	at com.midea.mideacopilot.codecompletions.DebouncedCodeCompletionProvider.getSuggestionDebounced(DebouncedCodeCompletionProvider.kt:69)
	at com.intellij.codeInsight.inline.completion.DebouncedInlineCompletionProvider.debounce(DebouncedInlineCompletionProvider.kt:77)
	at com.intellij.codeInsight.inline.completion.DebouncedInlineCompletionProvider$debounce$1.invokeSuspend(DebouncedInlineCompletionProvider.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ClassNotFoundException: com.intellij.codeInsight.inline.completion.suggestion.InlineCompletionSingleSuggestion PluginClassLoader(plugin=PluginDescriptor(name=MideaCopilot, id=com.midea.mideacopilot.chatgpt, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2023.3\plugins\MideaCopilot, version=0.0.2-201, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 9 more

**Comment by carlrobertoh** [comment]
Closing this issue since the Inline Completion API can only be used with platform version 2023.3 and later.
