### ISSUE TITLE
Something went wrong. Please try again later.

### ISSUE THREAD

**Issue by danilomarquesr12** [carlrobertoh/CodeGPT#81]
Before I was using a free trial and worked. After updating from 1.6 the error started.  I tried downgrade. Tried changing the model.
Tried upgrading openai account. I am an using api key from a paid account. 
Nothing solved.

For every message I sent, I only receive: 
![image](https://user-images.githubusercontent.com/119597946/230904499-729218bb-fcb3-4395-83ae-b462855977fb.png)

Only stacktrace I was able to collect related to the plugin:
```log
2023-04-10 09:40:37,736 [  10485]   INFO - #c.i.r.OsRegistryConfigProvider - OS provided value for 'enabled' is not found
2023-04-10 09:40:37,758 [  10507]   INFO - PerformancePlugin - Performance Plugin is in silent mode
2023-04-10 09:40:38,617 [  11366]   INFO - #c.i.u.j.JBCefApp - JCEF-sandbox is enabled
2023-04-10 09:40:38,664 [  11413]   INFO - #c.i.u.j.JBCefApp - jcef version: 104.4.26.633.0bc64e4cd9c16c88d2a0eb09dd792cbd2a0f13c6 | cmd args: [--disable-features=SpareRendererForSitePerProcess, --disable-gpu-process-crash-limit]
2023-04-10 09:40:38,758 [  11507]   INFO - STDOUT - JCEF(40:38:758): initialized stderr logger, severity=LOGSEVERITY_DISABLE
2023-04-10 09:40:38,883 [  11632]   WARN - #c.i.o.a.i.ActionToolbarImpl - 'NAVIGATION_BAR_TOOLBAR' toolbar by default uses any focused component to update its actions. Toolbar actions that need local UI context would be incorrectly disabled. Please call toolbar.setTargetComponent() explicitly.
java.lang.Throwable: toolbar creation trace
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.<init>(ActionToolbarImpl.java:131)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.<init>(ActionToolbarImpl.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbarImpl(ActionManagerImpl.java:397)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:461)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:456)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowPanel.createActionToolbar(ChatToolWindowPanel.java:48)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowPanel.initialize(ChatToolWindowPanel.java:30)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowPanel.<init>(ChatToolWindowPanel.java:17)
	at ee.carlrobert.codegpt.toolwindow.ProjectToolWindowFactory.createToolWindowContent(ProjectToolWindowFactory.java:18)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:548)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:527)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:983)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:920)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:906)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1094)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:176)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-04-10 09:40:39,034 [  11783]   INFO - #c.i.s.p.SettingsSyncPluginManager - Updated component state by the state of IDE.
No changes: {ChatGPT=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform, org.intellij.plugins.markdown]), com.github.evgenys91.machinet=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform, com.intellij.modules.lang, com.intellij.modules.java, org.jetbrains.kotlin]), com.plugin.chatgpt=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform]), com.yujunyang.intellij.plugin.sonar=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform, com.intellij.modules.lang, com.intellij.modules.java, Git4Idea]), ee.carlrobert.chatgpt=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform]), org.sonarlint.idea=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.lang])}

2023-04-10 09:40:39,081 [  11830]   INFO - #c.i.s.GitSettingsLog - Applying settings changes to branch ide: options/debugger.xml, options/baseRefactoring.xml, options/ide.general.xml, options/colors.scheme.xml, options/vcs.xml, ...

```

**Comment by carlrobertoh** [comment]
Hi, are you using the latest version(1.10.0)? I added some more logging which might help me detecting the issue.

**Comment by danilomarquesr12** [comment]
I upgraded to 1.10.0. Also using Intellij 2023.1.

Found this error more on the logs. 
2023-04-10 15:29:42,998 [ 445606]   FINE - #c.i.u.s.SvgTranscoder - 
org.w3c.dom.DOMException: property.syntax.error.at [/C:/Users/QPCJZ/AppData/Roaming/JetBrains/IntelliJIdea2023.1/plugins/CodeGPT/lib/instrumented-CodeGPT-1.10.0.jar, font-weight, none, invalid.identifier [font-weight, none]]
	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:759)
	at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:851)
	at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
	at org.apache.batik.bridge.CSSUtilities.convertDisplay(CSSUtilities.java:564)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:191)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:156)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:204)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:156)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:81)
	at com.intellij.ui.svg.SvgTranscoder$Companion.createImage(SvgTranscoder.kt:86)
	at com.intellij.util.SVGLoader.load(SVGLoader.kt:164)
	at com.intellij.ide.plugins.newui.HiDPIPluginLogoIcon.loadSVG(HiDPIPluginLogoIcon.java:96)
	at com.intellij.ide.plugins.newui.PluginLogo.loadFileIcon(PluginLogo.java:395)
	at com.intellij.ide.plugins.newui.PluginLogo.tryLoadIcon(PluginLogo.java:359)
	at com.intellij.ide.plugins.newui.PluginLogo.tryLoadJarIcons(PluginLogo.java:303)
	at com.intellij.ide.plugins.newui.PluginLogo.loadPluginIcons(PluginLogo.java:232)
	at com.intellij.ide.plugins.newui.PluginLogo.lambda$schedulePluginIconLoading$2(PluginLogo.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-10 15:29:42,998 [ 445606]   FINE - java.awt.mixing.Container - this = com.intellij.ide.plugins.newui.ListPluginComponent$2[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.5,border=com.intellij.ide.ui.laf.darcula.ui.DarculaCheckBoxBorder@65f956f4,flags=16777568,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=com.intellij.util.ui.JBInsets$JBInsetsUIResource[top=2,left=2,bottom=2,right=2],paintBorder=false,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=]
2023-04-10 15:29:42,998 [ 445606]   FINE - #c.i.u.s.SvgTranscoder - 
org.w3c.dom.DOMException: property.syntax.error.at [/C:/Users/QPCJZ/AppData/Roaming/JetBrains/IntelliJIdea2023.1/plugins/CodeGPT/lib/instrumented-CodeGPT-1.10.0.jar, font-size, none, invalid.identifier [font-size, none]]
	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:759)
	at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:851)
	at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
	at org.apache.batik.bridge.CSSUtilities.convertDisplay(CSSUtilities.java:564)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:191)


If you want my full intellij logs or that I test some action to see what logs are generated. That's fine.

**Comment by carlrobertoh** [comment]
The error seems to be in loading the svg icon, altho I doubt that's the main reason.
Could you try installing the pre-release package and see if anything changes?
https://github.com/carlrobertoh/CodeGPT/releases/tag/1.10.1

**Comment by carlrobertoh** [comment]
Will re-open on new updates.
