### ISSUE TITLE
IDE error

### ISSUE THREAD

**Issue by Stereo2025** [carlrobertoh/CodeGPT#85]
I have community/pycharm-community-edition 2023.1-1, pycharm was updated yesterday and the plugin stopped working, Exception in plugin CodeGPT(1.10.1) This plugin is not a product JetBrains. any idea how to fix it?

java.lang.Throwable: no jcef in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.ui.jcef.JBCefApp.<init>(JBCefApp.java:96)
	at com.intellij.ui.jcef.JBCefApp$Holder.init(JBCefApp.java:380)
	at com.intellij.ui.jcef.JBCefApp$Holder.<clinit>(JBCefApp.java:360)
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:342)
	at com.intellij.ui.jcef.JCEFHtmlPanel.<clinit>(JCEFHtmlPanel.java:17)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabHtmlPanel.createUIComponents(ChatToolWindowTabHtmlPanel.java:163)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabHtmlPanel.$$$setupUI$$$(ChatToolWindowTabHtmlPanel.java)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowTabHtmlPanel.<init>(ChatToolWindowTabHtmlPanel.java:41)
	at ee.carlrobert.codegpt.toolwindow.chat.ToolWindowTabPanelFactory.getTabPanel(ToolWindowTabPanelFactory.java:11)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowPanel.initialize(ChatToolWindowPanel.java:21)
	at ee.carlrobert.codegpt.toolwindow.chat.ChatToolWindowPanel.<init>(ChatToolWindowPanel.java:17)
	at ee.carlrobert.codegpt.toolwindow.ProjectToolWindowFactory.createToolWindowContent(ProjectToolWindowFactory.java:18)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:548)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:527)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:983)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:920)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:629)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:599)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1979)
	at com.intellij.openapi.wm.impl.SquareAnActionButton.setSelected(SquareStripeButton.kt:156)
	at com.intellij.ui.ToggleActionButton.actionPerformed(ToggleActionButton.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:228)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:207)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:207)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:518)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:614)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by carlrobertoh** [comment]
Weirdly the Java JCEF lib has gone missing after the update. The plugin was already up-to-date before you upgraded the IDE? Also what OS are you using?

**Comment by Stereo2025** [comment]
I am using linux manjaro.
No, I saw that the PyCharm IDE was updated, initiated the update, "-Syu", after the update I went to the IDE and saw that the plugin was also updated and has version 1.10.1, I updated it and then caught this error

**Comment by carlrobertoh** [comment]
The plugin received major UI changes from version 1.9.0 and is using the CEF browser now, I assume you were using older version of the plugin.
Could you try following [these steps](https://intellij-support.jetbrains.com/hc/en-us/articles/360016421559-JCEF-the-missing-libs-problem-on-Linux) and let me now if it works?

**Comment by Stereo2025** [comment]
I checked, the terminal answered that this library is present in the system, reinstalled it just in case.
It turns out the matter is in the system library, I'll go look for information.

➜  ~ ldconfig -p | grep libXss.so.1
	                      libXss.so.1 (libc6,x86-64) => /usr/lib/libXss.so.1
	                      
➜  ~ sudo pacman -Ss libXss        
        extra/libxss 1.2.3-4 [installed]
        X11 Screen Saver extension library

**Comment by veselkamarinova** [comment]
I had the same problem on arch linux. I solved it by replacing the standard package pycharm-community-edition with pycharm-community-jre from the AUR.
